name: 'lvh-run'
description: 'Runs LVH VMs for Mimic CI testing'
inputs:
  test-name:
    description: 'Unique test name'
    required: true
  lvh-version:
    description: 'LVH cli version (Docker tag)'
    required: true
    default: 'v0.0.28'
  cmd:
    description: 'Commands to run in a VM (any occurance of "$" within "cmd" must be escaped)'
    required: true
  ssh-port:
    description: 'SSH port for VM on a host'
    required: true
    default: '2222'
  ssh-connect-wait-retries:
    description: 'Number of retries to connect to the SSH server'
    required: true
    default: '300'
  ssh-connect-wait-timeout:
    description: 'Timeout in seconds between retries to connect to the SSH server'
    required: true
    default: '1'
  host-mount:
    description: 'Host dir path to mount in /host dir of a VM'
    required: true
  provision:
    description: 'Provision VM (if set to false, only given test cmd is going to be run)'
    required: true
    default: 'true'
  install-dependencies:
    description: 'Install QEMU dependencies (Debian/Ubuntu)'
    default: 'false'
  serial-port:
    description: 'Serial port to access VM'
    required: true
    default: '0'
  cpu:
    description: 'CPU count'
    required: false
  mem:
    description: 'RAM size'
    required: false
  cpu-kind:
    description: 'CPU kind to use'
    required: true
    default: 'host'
  image-path:
    description: 'Path to root image to boot with'
    required: true
  kernel-path:
    description: 'Path to kernel image to boot with'
    required: false
  verbose:
    description: 'Run in verbose mode'
    required: true
    default: 'false'
  port-forward:
    description: 'Additional to SSH comma-separated port forwards ($LOCAL:$VM_PORT)'
    required: false
  arch:
    description: 'VM architecture (amd64 (default) or arm64)'
    default: 'amd64'
    required: false
  kernel-version:
    description: 'Kernel version (if empty, a kernel from the image will be used)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Install LVH CLI
      id: install-lvh-cli
      if: ${{ inputs.provision == 'true' }}
      uses: ./.github/actions/lvh-install-cli
      with:
        arch: ${{ inputs.arch }}
        lvh-version: ${{ inputs.lvh-version }}
    - name: Load install packages from GitHub cache
      if: ${{ inputs.provision == 'true' && inputs.install-dependencies == 'true' }}
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: package-cache
      with:
        path: /tmp/.ubuntu-pkgs
        key: lvh-pkgs-${{ runner.os }}-${{ steps.install-lvh-cli.outputs.runner_os_id }}-${{ steps.install-lvh-cli.outputs.dependency_list_sha }}
    - name: Download LVH dependencies
      if: ${{ inputs.provision == 'true' && inputs.install-dependencies == 'true' && steps.package-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        n=0
        until [ "$n" -ge 5 ]; do
          success=1
          sudo apt update && \
          sudo apt-get clean && \
          sudo apt-get -d -y --no-install-recommends install ${{steps.install-lvh-cli.outputs.dependency_list}} && \
          break || success=0
          n=$((n+1))
          sleep 1
        done
        [ $success -eq 1 ] || exit 42
        sudo mkdir -p /tmp/.ubuntu-pkgs
        sudo cp /var/cache/apt/archives/*.deb /tmp/.ubuntu-pkgs
    - name: Install dependencies
      if: ${{ inputs.provision == 'true' && inputs.install-dependencies == 'true' }}
      shell: bash
      run: |
        # Disable auto update of man-db for every package
        sudo rm -f /var/lib/man-db/auto-update
        sudo cp /tmp/.ubuntu-pkgs/*.deb /var/cache/apt/archives/
        sudo apt-get -y --no-install-recommends install /tmp/.ubuntu-pkgs/*.deb
        sudo kvm-ok
    - name: Start VM
      if: ${{ inputs.provision == 'true' }}
      shell: bash
      run: |
        extraArgs=()
        if [ ! -z "${{ inputs.kernel-path }}" ]; then
          extraArgs+=("--kernel" "${{ inputs.kernel-path }}")
        fi
        if [ "${{ inputs.verbose }}" == "true" ]; then
          extraArgs+=("--verbose")
        fi
        if [ "${{ inputs.port-forward }}" != "" ]; then
          fwds=($(echo "${{ inputs.port-forward }}" | tr "," "\n"))
          for fwd in "${fwds[@]}"; do
            extraArgs+=("-p" "$fwd")
          done
        fi
        if [ ! -z "${{ inputs.cpu-kind }}" ]; then
          extraArgs+=("--cpu-kind" "${{ inputs.cpu-kind }}")
        fi

        sudo touch /tmp/console.log
        # Determine the amount of cpu and memory to allocate
        CPU=${{ inputs.cpu }}
        if [ -z "$CPU" ]; then
          CPU=$(nproc)
          echo "cpu unspecified, defaulting to nprocs CPUs: $CPU"
        fi
        MEM=${{ inputs.mem }}
        if [ -z "$MEM" ]; then
          # Default to 75% of the host memory
          MEM="$(free -m | awk '/^Mem:/{print int($2 * 0.75)}')M"
          echo "mem unspecified, defaulting ot 75% of host memory: $MEM"
        fi
        sudo lvh run --host-mount=${{ inputs.host-mount }} --image ${{ inputs.image-path }} \
            --daemonize -p ${{ inputs.ssh-port }}:22 --serial-port ${{ inputs.serial-port }} \
            --cpu=$CPU --mem=$MEM \
            --console-log-file /tmp/console.log \
            --qemu-arch ${{ inputs.arch }} \
            ${extraArgs[@]}
    - name: Wait for VM's SSH Server
      if: ${{ inputs.provision == 'true' }}
      shell: bash
      run: |
        n=0
        success=0
        until [ "$n" -ge ${{ inputs.ssh-connect-wait-retries }} ]; do
          if ssh -p ${{ inputs.ssh-port }} -o "StrictHostKeyChecking=no" root@localhost exit; then
            success=1
            break
          fi
          n=$((n+1))
          sleep ${{ inputs.ssh-connect-wait-timeout }}
        done
        if [ $success -eq 0 ]; then
          cat /tmp/console.log
          exit 42
        fi
    - name: Run test cmd in VM
      shell: bash
      run: |
        ssh -p ${{ inputs.ssh-port }} -o "StrictHostKeyChecking=no" root@localhost << EOF
        set -eu

        ${{ inputs.cmd }}
        EOF
