#!/bin/sh
set -e

uname_ver=6.9.10
ver=6.9.10-1
: ${DEBIAN_MIRROR:="http://deb.debian.org/debian"}

do_thing() {
  local arch="$1"
  local debian_arch="$2"
  local uname_variant="$3"
  local suffix="$4"
  local arch_macro="$5"
  local url="$DEBIAN_MIRROR/pool/main/l/linux/linux-image-${uname_ver}-${uname_variant}${suffix}_${ver}_${debian_arch}.deb"

  echo $url
  mkdir -p "out/$debian_arch"
  (
    cd "out/$debian_arch"
    [ -f "$debian_arch.deb" ] || curl -Lf "$url" >"$debian_arch.deb"
    ar xf "$debian_arch.deb"
    tar xf data.*
  )

  # TODO: extract vmlinux.h
  BOOT_DIR="out/$debian_arch/boot" VMLINUX_SUFFIX="-${uname_ver}-${uname_variant}" \
    tools/vmlinux-to-btf "out/$debian_arch"

  /usr/sbin/bpftool btf dump file "out/$debian_arch/vmlinux" format c >"out/$debian_arch/vmlinux.h"
}

echo $ver_rel $ver
do_thing x86_64 amd64 amd64 "-unsigned" "defined(__x86_64__)"
do_thing aarch64 arm64 arm64 "-unsigned" "defined(__aarch64__)"
do_thing riscv64 riscv64 riscv64 "" "defined(__riscv__) && __riscv_xlen == 64"
do_thing ppc64el ppc64el powerpc64le "" "defined(__powerpc64__) && defined(__LITTLE_ENDIAN__)"
