name: 'Build .deb Packages'

on:
  workflow_dispatch:
  push:

jobs:
  build-bookworm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: -b -us -uc
          docker-image: debian:bookworm-slim
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: bookworm
          path: debian/artifacts/*.deb
  build-noble:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: -b -us -uc
          docker-image: ubuntu:noble
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mantic
          path: debian/artifacts/*.deb

