name: Release actions

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-deb:
    name: Build .deb packages for ${{ matrix.distro.name }} (${{ matrix.arch }})
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        distro:
          - name: Debian 12
            codename: bookworm
            image: debian:bookworm-slim
            extra-repos: |
              deb http://deb.debian.org/debian bookworm-backports main
            extra-cmd-amd64: |
              sed -i 's/clang/clang-16/' debian/control
              sed -i 's/BPF_CC=clang/BPF_CC=clang-16 COMPAT_LINUX_6_1=1/' debian/rules
            extra-cmd-arm64: |
              sed -i 's/linux-source/linux-source-6.1/' debian/control
              sed -i 's/BPF_CC=clang/BPF_CC=clang COMPAT_LINUX_6_1=1/' debian/rules
          - name: Debian 13
            codename: trixie
            image: debian:trixie-slim
            extra-cmd-arm64: |
              sed -i 's/linux-source,/linux-source | linux-source-6.11 | linux-source-6.12,/' debian/control
          # - name: Debian 14 (testing)
          #   codename: forky
          #   image: debian:forky-slim
          - name: Ubuntu 24.04
            codename: noble
            image: ubuntu:noble
            extra-repos-amd64: |
              deb http://archive.ubuntu.com/ubuntu noble-backports main restricted universe multiverse
            extra-repos-arm64: |
              deb http://ports.ubuntu.com/ubuntu-ports noble-backports main restricted universe multiverse
            extra-cmd-amd64: |
              sed -i 's/clang,/clang, llvm,/' debian/control
            extra-cmd-arm64: |
              sed -i 's/clang,/clang, llvm,/' debian/control
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run pre-building script
        run: ${{ matrix.arch == 'amd64' && matrix.distro.extra-cmd-amd64 || matrix.distro.extra-cmd-arm64 }}
      - name: Build
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: -b -us -uc
          docker-image: ${{ matrix.distro.image }}
          extra-repos: ${{ matrix.arch == 'amd64' && matrix.distro.extra-repos-amd64 || matrix.distro.extra-repos-arm64 || matrix.distro.extra-repos }}
          host-arch: ${{ matrix.arch }}
      - name: Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd debian/artifacts
          _files=($(find . -type f -name 'mimic*.deb' -printf '%P\n') $(find . -type f -name 'mimic*.ddeb' -printf '%P\n'))
          for _f in ${_files[@]}; do
            sudo mv "$_f" "${{ matrix.distro.codename }}_$_f";
            sha256sum "${{ matrix.distro.codename }}_$_f" > "../${{ matrix.distro.codename }}_$_f.sha256"
          done
          gh release upload $(sed 's|refs/tags/||' <(echo ${{ github.ref }})) ${_files[@]/#/${{ matrix.distro.codename }}_} ../*.sha256
